# Pandas Exercises

**Source of the Data: https://www.kaggle.com/chirin/africa-economic-banking-and-systemic-crisis-data/downloads/africa-economic-banking-and-systemic-crisis-data.zip/1**


The dataset will be valuable to those who seek to understand the dynamics of financial stability within the African context.

Content
The dataset specifically focuses on the Banking, Debt, Financial, Inflation and Systemic Crises that occurred, from 1860 to 2014, in 13 African countries, including: Algeria, Angola, Central African Republic, Ivory Coast, Egypt, Kenya, Mauritius, Morocco, Nigeria, South Africa, Tunisia, Zambia and Zimbabwe.



* caseA     number which denotes a specific country
* cc3A     three letter country code
* country    The name of the country
* year   The year of the observation
* systemic_crisis "0" means that no systemic crisis occurred in the year and "1" means that a systemic crisis occurred in the year.
* exch_usd    The exchange rate of the country vis-a-vis the USD
* domestic_debt_in_default   "0" means that no sovereign domestic debt default occurred in the year and "1" means that a sovereign domestic debt default occurred in the year
* sovereign_external_debt_default  "0" means that no sovereign external debt default occurred in the year and "1" means that a sovereign external debt default occurred in the year
* gdp_weighted_default    The total debt in default vis-a-vis the GDP
* inflation_annual_cpi    The annual CPI Inflation rate
* independence   "0" means "no independence" and "1" means "independence"
* currency_crises  "0" means that no currency crisis occurred in the year and "1" means that a currency crisis occurred in the year
* inflation_crises  "0" means that no inflation crisis occurred in the year and "1" means that an inflation crisis occurred in the year
* banking_crisis "no_crisis" means that no banking crisis occurred in the year and "crisis" means that a banking crisis occurred in the year


---
# Complete the Tasks Below
---

**1. Import pandas**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

# New Section

**2. Read in the african_econ_crises.csv**

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Inteligência Artificial/Semana 1/exercícios/originais/african_econ_crises.csv')
df

#output:
# 	case 	cc3 	country 	year 	systemic_crisis 	exch_usd 	domestic_debt_in_default 	sovereign_external_debt_default 	gdp_weighted_default 	inflation_annual_cpi 	independence 	currency_crises 	inflation_crises 	banking_crisis
#0 	1 	DZA 	Algeria 	1870 	1 	0.052264 	0 	0 	0.0 	3.441456 	0 	0 	0 	crisis
#1 	1 	DZA 	Algeria 	1871 	0 	0.052798 	0 	0 	0.0 	14.149140 	0 	0 	0 	no_crisis
#2 	1 	DZA 	Algeria 	1872 	0 	0.052274 	0 	0 	0.0 	-3.718593 	0 	0 	0 	no_crisis
# ...

      case  cc3   country  ...  currency_crises  inflation_crises  banking_crisis
0        1  DZA   Algeria  ...                0                 0          crisis
1        1  DZA   Algeria  ...                0                 0       no_crisis
2        1  DZA   Algeria  ...                0                 0       no_crisis
3        1  DZA   Algeria  ...                0                 0       no_crisis
4        1  DZA   Algeria  ...                0                 0       no_crisis
...    ...  ...       ...  ...              ...               ...             ...
1054    70  ZWE  Zimbabwe  ...                1                 0          crisis
1055    70  ZWE  Zimbabwe  ...                0                 0       no_crisis
1056    70  ZWE  Zimbabwe  ...                0                 0       no_crisis
1057    70  ZWE  Zimbabwe  ...                0                 0       no_crisis
1058    70  ZWE  Zimbabwe  ...                0                 0       no_crisis

[1059 rows x 14 columns]

**3. Display the first 5 rows of the data set**

In [4]:
df.head()

#output:
# 	case 	cc3 	country 	year 	systemic_crisis 	exch_usd 	domestic_debt_in_default 	sovereign_external_debt_default 	gdp_weighted_default 	inflation_annual_cpi 	independence 	currency_crises 	inflation_crises 	banking_crisis
#0 	1 	DZA 	Algeria 	1870 	1 	0.052264 	0 	0 	0.0 	3.441456 	0 	0 	0 	crisis
#1 	1 	DZA 	Algeria 	1871 	0 	0.052798 	0 	0 	0.0 	14.149140 	0 	0 	0 	no_crisis
#2 	1 	DZA 	Algeria 	1872 	0 	0.052274 	0 	0 	0.0 	-3.718593 	0 	0 	0 	no_crisis
#3 	1 	DZA 	Algeria 	1873 	0 	0.051680 	0 	0 	0.0 	11.203897 	0 	0 	0 	no_crisis
#4 	1 	DZA 	Algeria 	1874 	0 	0.051308 	0 	0 	0.0 	-3.848561 	0 	0 	0 	no_crisis

   case  cc3  country  ...  currency_crises  inflation_crises  banking_crisis
0     1  DZA  Algeria  ...                0                 0          crisis
1     1  DZA  Algeria  ...                0                 0       no_crisis
2     1  DZA  Algeria  ...                0                 0       no_crisis
3     1  DZA  Algeria  ...                0                 0       no_crisis
4     1  DZA  Algeria  ...                0                 0       no_crisis

[5 rows x 14 columns]

**4. How many countries are present in this data set?**

In [5]:
df.country.nunique()

#output: 13

13

**5. Which countries are present in this data set?**

In [6]:
df.country.unique()

#output:
#array(['Algeria', 'Angola', 'Central African Republic', 'Ivory Coast',
#       'Egypt', 'Kenya', 'Mauritius', 'Morocco', 'Nigeria',
#       'South Africa', 'Tunisia', 'Zambia', 'Zimbabwe'], dtype=object)

array(['Algeria', 'Angola', 'Central African Republic', 'Ivory Coast',
       'Egypt', 'Kenya', 'Mauritius', 'Morocco', 'Nigeria',
       'South Africa', 'Tunisia', 'Zambia', 'Zimbabwe'], dtype=object)

**6. Which country had the highest annual CPI Inflation rate? What was the inflation rate?**

In [7]:
df.sort_values('inflation_annual_cpi', ascending=False).head(1)

#output:
# 	case 	cc3 	country 	year 	systemic_crisis 	exch_usd 	domestic_debt_in_default 	sovereign_external_debt_default 	gdp_weighted_default 	inflation_annual_cpi 	independence 	currency_crises 	inflation_crises 	banking_crisis
#1053 	70 	ZWE 	Zimbabwe 	2008 	1 	0.002 	1 	1 	0.0 	21989695.22 	1 	1 	1 	crisis

      case  cc3   country  ...  currency_crises  inflation_crises  banking_crisis
1053    70  ZWE  Zimbabwe  ...                1                 1          crisis

[1 rows x 14 columns]

**7. In what year did Kenya have its first sistemic crisis?**

In [8]:
df[(df.country == "Kenya") & (df.systemic_crisis)].sort_values('year', ascending=True).head(1)

#ouput:
# 	case 	cc3 	country 	year 	systemic_crisis 	exch_usd 	domestic_debt_in_default 	sovereign_external_debt_default 	gdp_weighted_default 	inflation_annual_cpi 	independence 	currency_crises 	inflation_crises 	banking_crisis
#475 	35 	KEN 	Kenya 	1985 	1 	16.2843 	0 	0 	0.0 	11.398 	1 	0 	0 	crisis

     case  cc3 country  ...  currency_crises  inflation_crises  banking_crisis
475    35  KEN   Kenya  ...                0                 0          crisis

[1 rows x 14 columns]

**8. How many yearly systemic crisises have occurred per country?**

In [9]:
df.groupby(["country"]).sum().systemic_crisis

#output:
# country
# Algeria                      4
# Angola                       0
# Central African Republic    19
# Egypt                        6
# Ivory Coast                  4
# Kenya                       13
# Mauritius                    0
# Morocco                      2
# Nigeria                     10
# South Africa                 0
# Tunisia                      5
# Zambia                       4
# Zimbabwe                    15

country
Algeria                      4
Angola                       0
Central African Republic    19
Egypt                        6
Ivory Coast                  4
Kenya                       13
Mauritius                    0
Morocco                      2
Nigeria                     10
South Africa                 0
Tunisia                      5
Zambia                       4
Zimbabwe                    15
Name: systemic_crisis, dtype: int64

**9. How many years did a sovereign external debt default occur in Zimbabwe?**

In [10]:
df[(df.country == 'Zimbabwe') & (df.sovereign_external_debt_default == 1)].count().sovereign_external_debt_default

#sovereign_external_debt_default
#output: 30

30

**10. In which year did Algeria have its highest exchange rate?**

In [11]:
df[df.country == "Algeria"].sort_values('exch_usd', ascending=False).head(1)

#output:
#case 	cc3 	country 	year 	systemic_crisis 	exch_usd 	domestic_debt_in_default 	sovereign_external_debt_default 	gdp_weighted_default 	inflation_annual_cpi 	independence 	currency_crises 	inflation_crises 	banking_crisis
#84 	1 	DZA 	Algeria 	2014 	0 	87.970698 	0 	0 	0.0 	2.917 	1 	0 	0 	no_crisis

    case  cc3  country  ...  currency_crises  inflation_crises  banking_crisis
84     1  DZA  Algeria  ...                0                 0       no_crisis

[1 rows x 14 columns]